### ISSUE TITLE
Status boxes

### ISSUE THREAD

**Issue by Hains** [DMM-PLi/meta-dream#5]
Build:

DM7080 :   OK
DM520:      OK
DM820:      OK
DM900:      OK
DM500HD: OK

**Comment by persianpros** [comment]
For the start I have to admit we did great :)
I'm working on my build server now ...

**Comment by persianpros** [comment]
dm500hd: ok

**Comment by Hains** [comment]
DM900. 

meta-openpli/recipes-linux/linux-firmwares/firmware-rtl8188eu.bb
meta-openpli/recipes-connectivity/realtek/rtl8192cu

Fails to compile against dm900 3.14 kernel.

**Comment by Hains** [comment]
I have now
```
# CONFIG_RTL8188EU is not set
# CONFIG_RTL8191CU is not set
```
in defconfig.

**Comment by persianpros** [comment]
Check now ...

**Comment by Hains** [comment]
Ok now.

**Comment by Hains** [comment]
gstreamer-dvbmediasink doesn't recognize configure option --with-dreambox as warning.

**Comment by Hains** [comment]
I have to leave now for a few hours..I take a look at dvbmediasink then

**Comment by persianpros** [comment]
I have another problem: I did add this submodule but it won't be updated after https://github.com/DMM-PLi/dmm-bsp/tree/1f468a72f6763c8ac676b5fa2b04115f31ffb5e3

**Comment by Hains** [comment]
How do you update?  What command? Error?

**Comment by Hains** [comment]
No dm525hd box?

**Comment by persianpros** [comment]
MACHINE=... make update

dm525 is same as dm520 ;)

**Comment by Hains** [comment]
No that won't work. Because dmm-bsp is not in openpli layer.

in dmm-bsp
```
git pull origin master
```

**Comment by persianpros** [comment]
Oops my bad LOL.

**Comment by Hains** [comment]
Configure option --with-dreambox does not exist
[https://github.com/OpenPLi/gst-plugin-dvbmediasink/blob/gst-1.0/configure.ac]

Must be something from gstreamer1.0-plugin-multibox-dvbmediasink
Perhaps it better to use that mediasink instead of openpli.
And use openatv-dev branch.

**Comment by persianpros** [comment]
Please help me with https://github.com/persianpros/dmm-bsp/commit/bce9f81e1c2f889cc26c54043b4a239a4f881d72

**Comment by Hains** [comment]
I'm busy

**Comment by Hains** [comment]
Just add all missing modules to KERNEL_BUILTIN_MODULES_dm7020hdv2 = "\ 
in linux-dreambox.inc

**Comment by Hains** [comment]
Ah i see you done that..but the last one...ok...yes that the hard one.

But also this error 
ln: failed to create symbolic link '415660c1.0': File exists

**Comment by persianpros** [comment]
I think we're missing the point, The only extra thing dm7020hdv2 has is how it packed am I right?
dreambox-nand-1024mb-2k.inc instead of dreambox-nand-1024mb.inc so could we delete all dm7020hdv2 stuff and do:
1- Compile dm7020hd nfi image then zip it.
2- Remove the nfi as we have the zip.
3- Compile dm7020hd nfi but with dreambox-nand-1024mb-2k.inc this time.
4- Zip the new image with v2 at the end of it then delete the nfi.
5- Now we have both images in same folder and less time.

**Comment by Hains** [comment]
I consider this.
PRECOMPILED_ARCH_dm7020hdv2 = "dm7020hd"
and in dvb-module also. 

rootfs want dm7020hd stuff ????

I go futher in the evening. I had to go again.sorry

**Comment by Hains** [comment]
Or rename machine to e.g. 7020hdv2. It seems like machine name is limited to 8 characters.
Thus dm7020hdse == dm7020hd. ..pffff.. 
Probably the same problem with dm500hdv2 and dm800sev2.

**Comment by persianpros** [comment]
dm500hdv2/dm800sev2 and dm7020hd are ok, Also no need for https://github.com/Hains/dmm-bsp/commit/8d6c9c61a1f5c692aae15f8824e0144033e58cbd
dm7020hdv2 is same as dm7020hd with only "dreambox-nand-1024mb-2k.inc" instead of "dreambox-nand-1024mb.inc" thats all!
I'll find a fast way for dm7020hdv2 don't worry :)

**Comment by Hains** [comment]
Do you have eglibc 2.18 for dm800. I don't
I ask someone who has it. But no respons yet.

**Comment by persianpros** [comment]
What's the exact name of the file that you need?

**Comment by Hains** [comment]
recipe eglibc_2.18.bb (and patches).  But version 2.19 can also be used i heard. I'm not sure.

**Comment by Hains** [comment]
I found something..Should we add them to the dmm-bsp layer?http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-core/eglibc/eglibc_2.18.bb?h=dora

**Comment by persianpros** [comment]
If it help yes, Did you test dm800 build?

**Comment by Hains** [comment]
I busy, i need glibc, i try to grab them from that snapshot. Perhaps there are more recipes, wifi ??
I contact fairbird who build dm800 against openpli-oe-core.

**Comment by Hains** [comment]
dm800 is very tricky..due to older glibc, glibc-networking needs to be downgraded to 2.46.
Current version in openembedded-core 2.48 and higher doesn't compile.

**Comment by Hains** [comment]
Much better now latest changes in git.thanks

**Comment by persianpros** [comment]
Your welcome my friend :)
It was such pain in ... now I can rest ...

**Comment by Hains** [comment]
Yes i could be unclear for someone. But later...
But dm800 is 100x more pain in the .....
It needs a lot of files for meta-openpli and openembedded-core..
Older eglibc,, gcc6 patches..which don't work with kernel 2.6.28 ????
I think you have to downgrade/rework half openembedded-core/meta-openpli to get that box build.

**Comment by Hains** [comment]
https://github.com/Hains/dmm-bsp/commit/19db4b10b6dcbefd250caf32ae120ac6df7b14ca

Do you have better solution for build failure dm7080.
```
install: cannot stat './vmlinux.bin': No such file or directory
```

**Comment by persianpros** [comment]
Not yet but seems like a bug: https://patchwork.openembedded.org/patch/138234/

**Comment by persianpros** [comment]
dm820/dm7080 problems are related to: https://github.com/DMM-PLi/meta-dream/blob/master/recipes-bsp/linux/linux-extra-image.inc

**Comment by persianpros** [comment]
I think I can fix the dm820/dm7080 kernel problem just give me 1 day ...

**Comment by persianpros** [comment]
OK found the problem: https://github.com/openembedded/openembedded-core/commit/413a5faf99280f4e083358e4134aebbcfa47bb4c

PLi's OE isn't recent enough, OE-A and DMM are using newer versions of OE.

**Comment by Hains** [comment]
There is a problem with dm7020hd.

When flash:

INVALID IMAGE(YOU NEED A DM7020HD IMAGE).

**Comment by persianpros** [comment]
Did you try dm7020hd or dm7020hdv2 ?
Test both please.

**Comment by Hains** [comment]
dm7020hd. Report from OpenPLi forum user with dm7020hd.

When using the old dm7020hd.conf(before smart way commit), flashing ok.

**Comment by Hains** [comment]
Wait..I see..He's missing change in Makefile..

**Comment by persianpros** [comment]
"EXACTNAME" must be in Makefile otherwise it won't work.

**Comment by Hains** [comment]
The change in Makefile is a bit unclear i think. Line numbers are missing and there is a missing '+' in
```
@echo 'export EXACTNAME' >> $@
```
It is much clearer for most people to see the  patch with line numbers.
```
diff --git a/Makefile b/Makefile
index 1d22d8d2..3101f5df 100644
--- a/Makefile
+++ b/Makefile
@@ -112,6 +112,13 @@ all: init
 $(BBLAYERS):
 	[ -d $@ ] || $(MAKE) $(MFLAGS) update
 
+EXACTNAME = $(MACHINE)
+export EXACTNAME
+ifeq ($(MACHINE),dm7020hdv2)
+MACHINE=dm7020hd
+EXACTNAME=dm7020hdv2
+endif
+
 initialize: init
 
 init: $(BBLAYERS) $(CONFFILES)
@@ -151,6 +158,9 @@ $(TOPDIR)/env.source: $(DEPDIR)/.env.source.$(BITBAKE_ENV_HASH)
 	@echo 'export BB_ENV_EXTRAWHITE="MACHINE"' > $@
 	@echo 'export MACHINE' >> $@
 	@echo 'export PATH=$(CURDIR)/openembedded-core/scripts:$(CURDIR)/bitbake/bin:$${PATH}' >> $@
+	@echo 'export BB_ENV_EXTRAWHITE="MACHINE EXACTNAME"' > $@
+	@echo 'export MACHINE' >> $@
+	@echo 'export EXACTNAME' >> $@
 
 OPENPLI_CONF_HASH := $(call hash, \
 	'OPENPLI_CONF_VERSION = "1"' \
```

**Comment by persianpros** [comment]
Yeah you're right, If it's not better now please update it :)

**Comment by Hains** [comment]
That's better. I will add line numbers.

**Comment by persianpros** [comment]
@echo 'export BB_ENV_EXTRAWHITE="MACHINE"' > $@
should be replaced with
@echo 'export BB_ENV_EXTRAWHITE="MACHINE EXACTNAME"' > $@

**Comment by Hains** [comment]
The code
```
EXACTNAME = $(MACHINE)
export EXACTNAME
```

Doesn't work in Makefile. therefore the bb.utils.contains construction is always false, and bitbake will always pick up the dm7020hdv2 code even when build for dm7020hd..

Add
```
EXACTNAME = "${MACHINE}"
```
To meta-openpli/conf/layer.conf does work well . exactname is always machinename, like now. Thus no problem, right?

In Makefile only
```
ifeq ($(MACHINE),dm7020hdv2)
MACHINE=dm7020hd
endif
```

**Comment by persianpros** [comment]
What about https://github.com/DMM-PLi/meta-dream/blob/master/conf/layer.conf ? Do we have to use openpli layer.conf ?

**Comment by Hains** [comment]
Yes apparently, unless you know a proper solution. I try a lot,but i succeeded with layer.conf only.

**Comment by Hains** [comment]
Nevermind....

**Comment by Hains** [comment]
I will try it..

**Comment by Hains** [comment]
Yes that works.. I change it..

**Comment by persianpros** [comment]
Thanks a lot 👍

**Comment by Hains** [comment]
```
Now if you want to build for dm7020hd/dm7020hdv2 edit the "Makefile" file(line 112):
```
Edit Makefile in now actually required for dm7020hdv2 only, 
Or should we let it this way?

**Comment by persianpros** [comment]
Are you sure? dm7020hd boots without Makefile changes?

**Comment by Hains** [comment]
Yes 99,9 %
To be 100% sure, i can ask the owner of dm7020hd to test.

**Comment by Hains** [comment]
To be clear:

The last succesfull test with dm7020hd was.

-EXACTNAME in meta-openpli/conf/layer.conf.

Changes in Makefile: how it's now in our meta-dream description.Thus no exactname in Makefile.

I simulated exactname with bb.utils.contain, and that was working well, in both layer.conf's.
But not in Makefile.

**Comment by persianpros** [comment]
I think this is wrong: https://github.com/DMM-PLi/meta-dream/commit/a579f38fd45d246d3a94def40387e85fde865f66
because we need EXACTNAME in https://github.com/DMM-PLi/meta-dream/blob/master/conf/machine/dm7020hd.conf and https://github.com/DMM-PLi/meta-dream/blob/master/recipes-bsp/drivers/dreambox-secondstage.inc but now there is no EXACTNAME and it's empty so dm7020hd would be ok but dm7020hdv2 no ...

**Comment by Hains** [comment]
EXACTNAME is in meta-dream/conf/layer.conf.

Not tested yet with dm7020hd, but with EXACTNAME in meta-openpli/conf/layer.conf it works..

Without EXACTNAME  dm7020hd is being build as dm7020hdv2.

**Comment by persianpros** [comment]
You don't get what I mean,
MACHINE must be dm7020hd for both but EXACTNAME must be dm7020hdv2 for dm7020hdv2 otherwise it will make dm7020hd secondstage and image, For example: https://github.com/DMM-PLi/meta-dream/blob/master/recipes-bsp/drivers/dreambox-secondstage.inc

PR = "${@bb.utils.contains('EXACTNAME', 'dm7020hdv2', 'r${DATE}-v2', 'r${DATE}', d)}"

but you removed it here: https://github.com/DMM-PLi/meta-dream/commit/a579f38fd45d246d3a94def40387e85fde865f66#diff-04c6e90faac2675aa89e2176d2eec7d8L29

**Comment by Hains** [comment]
Ok i see the problem.I get it.

But it doesn't make sense to define EXACTNAME in Makefile, as it doesn't work.
With your way, dm7020hd will be built as dm7020hdv2.

**Comment by persianpros** [comment]
:(
Then we need to look deeper ...

**Comment by Hains** [comment]
In OE-Alliance they use
```
MACHINEOVERRIDES .= ":dreamboxv1"
```
So what about reverting the smart way and use:
```
MACHINEOVERRIDES .= ":dm7020hd"
```
in dm7080hdv2.conf. I did not try it yet, and it needs perhaps more changes?

Cause i don't know how to export EXACTNAME from makefile to meta-dream. I tried almost everything.

**Comment by Hains** [comment]
Yes..with MACHINEOVERRIDES image dm7020dmv2.

I revert your smart way.

No i only have to work on secondstage and dvb-modules. 
After fetching they need to be renenamed to v2.
In that way we can use MACHINE as many as possible.

No need to edit Makefile or whatever.

If i ready, i will create a new branch and push the big change to that branch.
You can take a look at at before pushing it to master.

**Comment by Hains** [comment]
https://github.com/DMM-PLi/meta-dream/commit/312290f6d27421f1f76c1d5fd79fed686e283ad0

and fix typo

https://github.com/DMM-PLi/meta-dream/commit/998e0672a73a785db2a8b0d3ac127af00b3a5500

in new dm7020hdv2 branch

**Comment by MastaG** [comment]
I almost have the dm800 fully working.
Quite a few packages required patching.

Only one issue left where the kernel doesn't seem to build a Module.symvers required for do_shared_workdir()

**Comment by persianpros** [comment]
Thanks a lot :)
I did invite you to be a member of "DMM-PLi" ;)

**Comment by Hains** [comment]
Houston, we have a problem.

Since the PR of MastaG, dm8000 and dm7020hd and probably more boxes doesn't boot anymore.
No Errors or warnings(except some regarding fetch mirror blablabla).
But boxes return in stop mode after flash.

With git checkout back to -before the PR-..Kernel rebuild and box boot flawless.

So, my suggestion is to make a seperate meta-dream for dm800. The dm800 needs a seperate build-envrionment anyway. Name it meta-dream-dm800 and clone it with
```
https://github.com/DMM-PLi/meta-dream.git meta-dream
```
I have no clue yet what causing this..dm8000/dm7020hd build with proper glibc, linux-libc-headers etc..So at first sight everything seems to be ok, but it isn't.

@Zeros did test for dm7020hd and reported it, I did test for dm8000 and confirm problem.

**Comment by Hains** [comment]
Apart from the problem.. Thanks a lot MastaG to bring dm800 back to life.

**Comment by MastaG** [comment]
I'll fix it  :)
Building the dm800 is a separate meta-dream is not required as its the only mips32el-nf receiver.
Please only undo the changes to dm8000.conf and dm7020.conf  (the splash screen can be a possible cause) also undo the changes to dreambox-dvb-modules.inc. then they should boot again :)

**Comment by Hains** [comment]
It's your changes in dvb-modules.inc indeed.
Just restore the line and box does boot.
```
@@ -38,4 +38,5 @@ DRIVERDATE = "${@'${PV}'.split('-')[-1]}"
 
 FILESEXTRAPATHS_prepend := "${THISDIR}/dreambox-dvb-modules:"
 
+FILES_${PN} += "${sysconfdir}/modules-load.d/${PN}.conf /lib/modules/${DM_LOCALVERSION}/extra"
 FILES_${PN} += "${sysconfdir}/modules-load.d/${PN}.conf /lib/modules/${DM_LOCALVERSION}/extra/LICENSE"
```

**Comment by Hains** [comment]
Are you agree with this patch? I have no dm800 build at this moment.
```
@@ -38,4 +38,4 @@ DRIVERDATE = "${@'${PV}'.split('-')[-1]}"
 
 FILESEXTRAPATHS_prepend := "${THISDIR}/dreambox-dvb-modules:"
 
-FILES_${PN} += "${sysconfdir}/modules-load.d/${PN}.conf /lib/modules/${DM_LOCALVERSION}/extra/LICENSE"
+FILES_${PN} += "${sysconfdir}/modules-load.d/${PN}.conf /lib/modules/${DM_LOCALVERSION}/extra"
```

**Comment by MastaG** [comment]
The dreambox-dvb-modules-dm800_xxx.bb does not include dreambox-dvb-modules.inc so you can leave that one as is, as the dm800 builds without issue.

Now regarding dreambox-dvb-modules.inc when you add /lib/modules/${DM_LOCALVERSION}/extra to FILES_${PN} you'll pack all the modules into the main package.. so for example dreambox-dvb-modules-dm800se_xxx.ipk will contain all .ko modules ans bitbake will not build separate packages like kernel-module-bcmxxxx.ipk.
The problem I got with this approach is that due to the "inherit module" in the dreambox-dvb-modules.inc the main package dreambox-dvb-modules-dm800se_xxxx.ipk will depend on these kernel-module-xxx.ipk packages.
However they're not built because they're added to the main package causing my openpli-enigma2-image to fail for the dm800se.
So I think if you choose to add the modules to the main package by adding them to FILES_${PN} you should remove the "inherit module" line.

However just revert dreambox-dvb-modules.inc for now and leave the dreambox-dvb-modules-dm800_xxx.bb as is :)

I'll look into it tonight.

**Comment by MastaG** [comment]
Now with the revert to dreambox-dvb-modules.inc.
Can you try to build a dm800se image?
I'm getting the following error at the final do_image stage.

Collected errors:
 * calculate_dependencies_for: Cannot satisfy the following dependencies for packagegroup-core-boot:
 * 	kernel-module-alps-bsbe1 * 	kernel-module-alps-bsbe1-c01a * 	kernel-module-alps-bsbe2 * 	kernel-module-bcm4506 * 	kernel-module-bcm7405 * 	kernel-module-cu1216mk3 * 	kernel-module-cxd1981 * 	kernel-module-dreambox-keyboard * 	kernel-module-dreambox-rc2 * 	kernel-module-helper * 	kernel-module-lcd * 	kernel-module-lnb-ctrl * 	kernel-module-si2166b * 	kernel-module-si2169c * 	kernel-module-stb-core * 	kernel-module-tmp100 * 	kernel-module-tu1216 * 
 * opkg_solver_install: Cannot install package packagegroup-core-boot.

You see the kernel-module-XXX are not built anymore due to the .ko files being part of the main package: dreambox-dvb-modules-dm800se_3.2-20151201.ipk now.
It's because you add their path to FILES_${PN}.

The reason why it "depends" on those kernel-module-XXX packages is because the dreambox-dvb-modules.inc has this line: "inherit module"
I think it needs to be changed to "inherit module-base".

But first I'm curious if curious if I'm the only one getting the above error when building an dm800se image.

**Comment by MastaG** [comment]
I already know why...
It's the linux kernel recipes-bsp/linux/linux-dreambox.inc

KERNEL_BUILTIN_MODULES_dm800se = "\
	kernel-module-block2mtd \
	kernel-module-stv0299 \
	"
KERNEL_BUILTIN_MODULES_dm7020hd = "\
	kernel-module-block2mtd \
	kernel-module-fuse \
	kernel-module-stv0299 \
	kernel-module-alps-bsbe1 \
	kernel-module-alps-bsbe1-c01a \
	kernel-module-alps-bsbe2 \
	kernel-module-bcm4506 \
	kernel-module-bcm7405 \ 
	kernel-module-cu1216mk3 \
	kernel-module-cxd1981 \
	kernel-module-dreambox-keyboard \
	kernel-module-dreambox-rc2 \
	kernel-module-helper \
	kernel-module-lcd \
	kernel-module-lnb-ctrl \
	kernel-module-si2166b \
	kernel-module-si2169c \
	kernel-module-stb-core \
	kernel-module-tmp100 \
	kernel-module-tu1216 \
	"

For the dm7020hd we tell it, that all those modules are builtin..

**Comment by MastaG** [comment]
Fixed, dm800se build succesfull and booting fine :)
https://github.com/DMM-PLi/meta-dream/pull/9

**Comment by persianpros** [comment]
@MastaG You have write access to the git so no need to send merge requests, You can push directly ;)

**Comment by MastaG** [comment]
Oh yeah of course.
Thank you :)

So I've built for dm800, dm800se, dm800sev2, dm500hd, dm500hdv2, dm7020hd and dm7020hdv2.

All succesful but I've only tested the dm800 and dm800se which are booting fine.
I dont own the others.

**Comment by persianpros** [comment]
Also you can make your membership public here: https://github.com/orgs/DMM-PLi/people (As we did)

Great job MastaG, Now we should wait for PLi's OE upgrade so we can build dm820/dm7080 images too.

**Comment by Hains** [comment]
MastaG: Welcome.

Persian Prince: I create test1 branch in meta-dream  to build against OpenPLi test1 branch.
That branch has latest pyro branch openembedded-core.
A lot newer than rc-6.0/develop.
Unfortunately vmlinux.bin still failed to install dm7080hd.
Be aware OpenPLi test1 branch and Meta-dream test1 branch does not build out of the box.
It need some changes regarding vsftp, gcc-cross, mediasink etc.

So vmlinux still not solved with newer OE-core.
Thus dm7080hd still not boot, OR user has to recover secondstage box before flash or so...?

**Comment by Hains** [comment]
I extract the image and the symlinks for vmlinux* are working.
I don't have a rc-6.0/develop build-env at this moment with current morty branch OE-core, but as far i remember they didn't work(it's a while ago).
I compare the image with a openATV image, and regarding the /boot directory there is not much different.
Our image has 3 bootlogo's included and the size of the vmlinux files are +/- 200 kb small/bigger, but they are just as in openatv 8,6 MB and 4,4 MB. 

So it seems ok now for dm7020hd, when build in OpenPLi test1 branch with newer pyro OE-core.

But it's still frustrated to have a next -gen OpenPLi image for dm7080, but no box to test.

Anyway, this is all i can do, and now waiting to build out of the box with test1 branch OpenPLi.

**Comment by MastaG** [comment]
What exactly is missing from the current OE-version for building the dm820/7080hd receivers?
Can't it be backported?
Reason why I'm asking is because I think the openpli-oe-core test1 branch might take a while to be merged into develop.
The new Oe-core version uses gcc-7 by default which (if I understood correctly) causes issues for many kernel recipes in many BSP-layers.
So unless decides to globally set gcc 6.x as the default compiler we have to wait for many BSP-layer partners to update for gcc-7 :)

**Comment by Hains** [comment]
No it gcc 6.3.0. 
You have to add
```
#Include subversion, mercurial and msgfmt(gettext) to hosttools
HOSTTOOLS += "svn hg msgfmt"
```
to meta-openpli/conf/layer.conf

-Add glib-2.0 glib-2.0-native as dependency to gstreamer1.0-plugin-subsink.bb

And vsftp need to be replaced, it will push it to meta-dream as backport.
And Samba need some changes in recipe. also push it to meta-dream

-with swig 3.12 Enigma2 need python-inmportlib as PYTHON_RDEPS. Otherwise enigma2 doesn't 
startup.
I can add it to enigma2.bbappend.

**Comment by MastaG** [comment]
Yeah.. Just backport it :)
You can always add some dmbackports option to MACHINE_FEATURES for dm7080 and dm820.

Then add a gstreamer1.0-plugin-subsink.bbappend with:
DEPENDS_append_dmbackports = " glib-2.0 glib-2.0-native"

PYTHON_RDEPS_append_dmbackports = " \
python-importlib \
"

etc...

**Comment by Hains** [comment]
These changes,vsftpd, python-importlib and samba, are for all machines(dreambox, vuduo, xtrend etc),

Yes, it could take a long time with test1 branch.It's waiting at bug.
https://bugzilla.yoctoproject.org/show_bug.cgi?id=11874

We shall see.

**Comment by Hains** [comment]
test1 branch should now build out of the box.
Not tested from scratch with these changes in meta-dream(i had them in meta-openpli).
Feel free to change something if you encounter problems.

Happy building.

**Comment by Hains** [comment]
New problem.
Image dm800se is too big

openpli-enigma2-homebuild-dm800se.rootfs.jffs2) is too big. This doesn't work. Sorry.Invalid data partition!

Even without samba.

**Comment by MastaG** [comment]
On openpli-oe-core develop or test1?
The develop branch is building fine here for my dm800se.
Tomorrow I'll commit my ucl/upx recipes for nativesdk and my bbclass for compressing many large binaries like /usr/bin/enigma2, oscam, openssl etc..
I'll add the smallflash machine_feature for this to the 64MB receivers.
Then we'll finally be able to enjoy some more flash space again :)

**Comment by Hains** [comment]
on test1.

**Comment by persianpros** [comment]
We have some checks regarding dm7020hd in "linux-dreambox-kernel.patch", Are we using them for dm7020hdv2 too?

And we have some patches with "apply=no" at the end, Can we just delete those lines?

**Comment by Hains** [comment]
hm..yes we need to patch the patch. I assume they use the same code and it's not a lot(7/8 times).
We can't use MACHINE=dm7020hd for dm7080hdv2. 

And the patches with "aplly=no" can be removed indeed. That was something still on my to do list.
Also support-gcc5.patch can be removed, not the fix-build-gcc5. patch

**Comment by Hains** [comment]
Are you busy with it?  Otherwise i do it tomorrow or thursday

**Comment by persianpros** [comment]
You can work on the patch, I'll do all the cleanups in both branches.

**Comment by persianpros** [comment]
I suggest we rename the master branch to develop so it follows the PLi's branch names, If you agree please do it if your upload speed is good.

**Comment by Hains** [comment]
Agree if it is possilble to rename master. 
I take a look at it when kernel patch is done.

**Comment by Hains** [comment]
I can make a copy of master branch. Name it develop and make it default.

**Comment by Hains** [comment]
And dm7080 still not boot.

**Comment by Hains** [comment]
Now develop branch is default.

**Comment by persianpros** [comment]
Thanks a lot, I did delete the master branch and now we follow PLi's names.

What's the problem with dm7080? As dm820 is similar to it, Does dm820 boot?

**Comment by Hains** [comment]
dm820 i don't know as we have no tester for that box.
dm7080 still same issue 
https://forums.openpli.org/topic/52108-dm7020hdv2-help-for-dmm-bsp/page-4#entry766483

**Comment by Hains** [comment]
It still think the image is ok. but user had to do recovery, flash with dreamup, flash original image first or so.

**Comment by Hains** [comment]
Last link, last comment. same problem with secondstage.

User had to turn power off and on to solve the problem, LOL.

**Comment by persianpros** [comment]
We have new updates: https://github.com/oe-alliance/oe-alliance-core/commits/4.0/meta-brands/meta-dream ...

**Comment by persianpros** [comment]
We have a new 4K ARM model "dm920" which is the upgraded version of dm900: https://github.com/opendreambox/opendreambox/commits/krogoth

I'm waiting for a stable status then I'll add the support

**Comment by persianpros** [comment]
Would you please test dm920 build?

**Comment by Hains** [comment]
Build running now..

**Comment by MastaG** [comment]
For the record, I think we're  going to skip Pyro and go straight to Rocko.
So I took some time to clean out the DM800 recipes (refactoring linux-libc-headers, kernel headers and stuff).
I've pushed it into the "rocko" branch.

So we can now build a working DM800HD image with gcc 7.2.0 ;)

openpli-oe-core still needs some work, you could try the "pyro" branch, or my pli-oe-core "rocko" branch :)

**Comment by Hains** [comment]
I'll merge commits in Rocko when build succeed.

PP:
dm920 openweb
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/pull/693

**Comment by persianpros** [comment]
Thanks a lot :)

**Comment by persianpros** [comment]
We have pyro and rocko branches but I want to know what's the real name of develop branch?

**Comment by MastaG** [comment]
We'll first release 6.1 which is based on morty.
After that openpli-oe-core's pyro branch will be renamed to rocko so I can start merging my patches into their repository.
So I think pyro will be skipped (but there's hasn't been made a hard decision on that yet).

So for the being I'm working on OE rocko since I'm limited in time.

**Comment by MastaG** [comment]
Oh yeahh.. I'm cloning my meta-dream (forked of this one) as "meta-dreambox"  so it doesn't get in the way with PLi's one :)

**Comment by Hains** [comment]
Can someone confirm a huge memory leak with glibc 2.26 and OScam.
My dm8000 is out of memory within 12 hours with glibc 2.26 in combination with OScam.
Workaround is to add configure option
```
EXTRA_OECONF += "--disable-experimental-malloc 
```

See:
https://www.phoronix.com/scan.php?page=news_item&px=glibc-malloc-thread-cache

e.g.
https://sourceware.org/ml/libc-help/2017-08/msg00019.html

It seems not working well for malloc mechanism in OScam:   oscam-string.c line 8.
```
bool cs_malloc(void *result, size_t size)
{
	void **tmp = result;
	*tmp = malloc(size);
	if(*tmp == NULL)
	{
		fprintf(stderr, "%s: ERROR: Can't allocate %zu bytes!", __func__, size);
	}
	else
	{
		memset(*tmp, 0, size);
	}
	return !!*tmp;
}
``
But i'm the only one so far and perhaps there is a better solution?

**Comment by MastaG** [comment]
Confirmed here as well.
I was already wondering why oscam would quit after a while on my DM800Se.
My C skills aren't good enough to fix such problem from within the oscam source.
So I'll add a bbappend for glibc 2.26 for now 👍 

Thanks Hains

**Comment by MastaG** [comment]
Another problem when using OE rocko is that RT5370/3070 based wireless sticks (including the builtin one) aren't working.
It seems to connect, but doesn't acquire an address using busybox' udhcpc client.
I've already tried to downgrade wpa-supplicant, but that doesn't seem to help.

**Comment by persianpros** [comment]
I'm not familiar with cherry-pick so please teach me how to do it for https://github.com/DMM-PLi/meta-dream/commit/49f01099368d8c3b95bda170da9b73f1aea15cb6? I want it to be in pyro and rocko too.

Also https://github.com/RaspberryPLi/meta-raspberrypi is ready, RPi devices are so cheap and good for software tests, In my opinion people should not spend so much money just to experience enigma2. I myself don't have an enigma2 STB but I want to develop PE (Persian Empire) images like before so the best thing for me is to run it on a RPi. It would be for develop only because it doesn't have DVB functions. If you're interested just try it on a https://www.raspberrypi.org/products/ (I have RPi3).

@MastaG Is UPX good for ARM? I want to enable it for RPi0 :)

**Comment by MastaG** [comment]
@persianpros 
Awesome, I didn't know there was enigma2 for RPi will, I own both the Pi2 and 3 :)
Does it support software descrambling with libdvbcsa? if so, then you should checkout this fork: https://github.com/glenvt18/libdvbcsa as it supports neon instructions for bitslicing

I've tried an older version of UPX before when I was still building PLi4 images and it would crash some binaries on certain ARM receivers.
Can't remember which ones though.
But wer're now using the latest UPX git release which contains many fixes for ARM platforms.
So you could try to remove the || [ "${TARGET_ARCH}" == "arm" ] statement from "classes/upx_compress.bbclass" and see if it works.

**Comment by Hains** [comment]
@PP for cherry-pick
```
git checkout pyro
git cherry-pick   49f01099368d8c3b95bda170da9b73f1aea15cb6
git push

git checkout rocko
git cherry-pick 49f01099368d8c3b95bda170da9b73f1aea15cb6
git push

**Comment by persianpros** [comment]
See what MiLo said about RPi devices: https://forums.openpli.org/topic/55070-trying-to-compile-on-raspberry/

I'm compiling Open PLi 6.x (develop=morty branch) for my RPi3 right now using https://github.com/RaspberryPLi/meta-raspberrypi which I just added you as another owner ;)

We need to attach some USB DVB products and test the results but I'm affraid it would be still a development board nothing more :(

Anyway that's enough for my tests as I don't care about watching TV and streams, I just want to start developing PE images with my customized plugins ;)

**Comment by persianpros** [comment]
@Hains Thanks a lot :) Now I have to fix the conflicts which is not my thing, I'll commit the new updates separately.

**Comment by Hains** [comment]
Next time..

-Fix conflicts.
-git add <files>
-git commit
-git push

**Comment by Hains** [comment]
Done by myself. Driver update dm920 now in pyro and rocko, also PR fairbird.

**Comment by Hains** [comment]
MastaG can you sync meta-dreambox with meta-dream ? It's mixed with old and new stuff.
Or remove meta-dreambox?

**Comment by Hains** [comment]
Nevermind...I know what's wrong.

**Comment by Hains** [comment]
Pfffff.. Please remove meta-dream in your github, keep meta-dreambox.

**Comment by Hains** [comment]
Problems with kodi dreambox.
ERROR: Nothing RPROVIDES 'virtual/kodi' (but /home/hains/test/pli-oe-core/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-kodi.bb RDEPENDS on or otherwise requires it)

Need help.

**Comment by Hains** [comment]
MastaG. Can you also delete meta-dreambox and include this repo as submodule. 
Now i have 3 meta-dream's. Two in your pli repo pli and this one.

**Comment by MastaG** [comment]
Hains my friend.
I clone my own meta-dream (forked from this meta-dream into pli-oe-core as "meta-dreambox".
The local meta-dream in my pli-oe-core is from OpenPLi but shouldn't get added to the bblayers since I've removed it from the Makefile.

Reason I'm keeping PLi's meta-dream is so that it doesn't give me merge conflicts whenever they decide to change something to it.

Reason why I'm using my forked meta-dream (instead of this one), is the bbappend for openwebif.
I also like to build for fulan sh4 (spark receivers) and therefor I've made the changes to the bbappend inside my pli-oe-core (as the one inside meta-dream doesn't contain the spark remotes..)

But I'll change it to keep things easy :) (spark is broken for the moment anyways).

FIXED :)

**Comment by MastaG** [comment]
But two bbappends for the openwebif causes problems.. 

ERROR:
 enigma2-plugin-extensions-openwebif-1+gitAUTOINC+eb6ba55608-r0 do_package: QA Issue: enigma2-plugin-extensions-openwebif-vxg is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]
ERROR: enigma2-plugin-extensions-openwebif-1+gitAUTOINC+eb6ba55608-r0 do_package: Fatal QA errors found, failing task.
ERROR: enigma2-plugin-extensions-openwebif-1+gitAUTOINC+eb6ba55608-r0 do_package: Function failed: do_package
ERROR: Logfile of failure stored in: /media/data2/pli-oe-core/build/tmp/work/vusolo2-oe-linux/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+eb6ba55608-r0/temp/log.do_package.9251
ERROR: Task (/media/data2/pli-oe-core/meta-openpli/recipes-openpli/e2openplugins/enigma2-plugin-extensions-openwebif.bb:do_package) failed with exit code '1'

So I either need to remove the bappend from my pli-oe-core or we remove it from here.. (and I'll add the patch to my pli-oe-core).

**Comment by Hains** [comment]
Ok, that makes thing clear.
For some users it's a bit complicated to remove, add and change thing, and as the script fails, yeh then your .....
You can add any box to openwebif.append in meta-dream, no problem as it doesn't break things of course.
Merge conflicts due to missing meta-dream, is very easy to solve in this case.
Just delete meta-dream after merge, and your done regarding conflicts meta-dream.

So if you don't mind, to add a local meta-xxx to your build-environment for box xxxx?
That save us some time to help users with broken script, local changes, files not found etc.....

Thanks.

**Comment by Hains** [comment]
Can you create one bbappend for all boxes and push it to meta-dream?

**Comment by MastaG** [comment]
Done

**Comment by Hains** [comment]
Thanks, that's a lot easier for everyone, especially for users.

**Comment by Hains** [comment]
Ne need to fork enigma2 for test dm900. The if(def)'s  boxtype == xxx is totally wrong for dm9x0,dm820 and dm7080. Enigma2 consider dm900 as dm8000/dm7020hd etc now.
I start this week with a fork in my own repo and try to make a start with the correct box checks.
The code in OpenATV is different of course, so it takes some time. 
When it's ok so far i push it to meta-dream.
When all ok, we have two option.
1) Use the fork from meta-dream.
2) Apply patches in enigma2.bb

**Comment by persianpros** [comment]
I don't like OpenATV enigma2 and other OE-A forks of enigma2, We need to provide patches for PLi's enigma2 otherwise it would be an OE-A image ...

**Comment by MastaG** [comment]
I think Hains meant to fork PLi's enigma2 to this DMM-PLi project, so we can easily add the ifdefs for the new dreambox models.
I also use a forked enigma2 for my pli-oe-core because I applied the patches for supporting the sexy analog clock in BlackHole skins :)

But adding another patch file to the enigma2.bbappend is also an option of course.

**Comment by persianpros** [comment]
It seems MastaG changed rocko again :)

**Comment by Hains** [comment]
Yep. The script is actually not necessary. It just update this submodule to git head and remove bbappend smbnetfs. 
But keep it, just in case.
But submodule vuduo fails to fetch. It seems git hashes meta-vuplus and meta-xtrend are mixed.
I had to remove meta-vuplus with git rm -rf meta-vuplus and remove meta-vuplus from Makefile.

**Comment by MastaG** [comment]
That's because I wanted to build fot Vu+, Mutant and Zgemma receivers as well.. and their BSP-layers required changes for gcc 7 as well.
So I forked them and switched to my own forks in my pli-oe-core.
Just do:
rm -Rf meta-gfutures meta-vuplus meta-zgemma
git pull
make init update

And it should switch to my forks.
Then you can create OE rocko images for Vu+ 4k, Zgemma H7 and HD51/VS1500 receivers as well (and enjoy kodi :P)

**Comment by MastaG** [comment]
Btw, Erik started cleaning out the pyro branch of the official openpli-oe-core repository.

Soon after the 6.1 release Erik will merge pyro into develop.
So I guess rocko will be on hold for a while.. 

I already merged openpli-oe-core/pyro into my own pyro branch and now we'll have some more core-members working on it.

So I'm going to add you two as admin of my pli-oe-core repository so you can commit directly as I'll be busy in the following days.

**Comment by MastaG** [comment]
Well I only own a HD51.. Kodi sortof works but doesn't properly play my hevc encoded videos.. so even there it needs some work ;)
But I'll see if I can get a dm920 once the prices drop a little more.

**Comment by MastaG** [comment]
Btw the Pyro branch of my pli-oe-core has been synced with PLi's openpli-oe-core.
Also I've cherry-picked the fixes from the meta-dream rocko brach into the pyro branch.
So using my pli-oe-core pyro branch we can now build an image and feed for the dm800hd as well :)

I suggest everyone starts looking into cherry-picking the rocko-stuff into pyro as well, because soon after PLi's 6.1 release they'll merge the pyro branch into develop :)

**Comment by Hains** [comment]
Done. all my commits in develop, pyro and rocko.
